name: Docker Three-tier-Project CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push-backend:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push backend image
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/dev/backend:${{ github.run_number }}

  build-and-push-frontend:
    name: Build & Push Frontend Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push frontend image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          build-args: |
            REACT_APP_API_BASE_URL=${{ secrets.API_BASE_URL }}
          tags: ${{ secrets.ECR_REGISTRY }}/dev/frontend:${{ github.run_number }}